services:
  lander:
    platform: linux/amd64
    image: chrysg.com/lander:latest
    pull_policy: never
    env_file:
      - .env.server.production
    ports:
      - "3001:3001"
    restart: unless-stopped
